<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>VRates</AssemblyName>
    <RootNamespace>VRates</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="6.0.0-be.733" />
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.733" />
  </ItemGroup>

</Project>
